refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{f}|{l}|{T}|{L}| {m}\n"
  logfile:
    kind: rolling_file
    path: "C:\\Users\\Conner Replogle\\Documents\\GitHub\\yeti\\yeti.log"
    policy:
      # Identifies which policy is to be used. If no kind is specified, it will
      # default to "compound".
      kind: compound
      # The remainder of the configuration is passed along to the policy's
      # deserializer, and will vary based on the kind of policy.
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: delete
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)}:{f}|{l}|{T}|{L}| {m}\n"
      
root:
  level: debug
  appenders:
    - logfile
    - stdout


