refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{f}|{l}|{T}|{L}| {m}\n"
  logfile:
    kind: file
    path: "C:\\Users\\allep\\dev\\Rust\\yeti\\yeti.log"
    encoder:
      pattern: "{f}|{l}|{T}|{L}| {m}\n"
root:
  level: debug
  appenders:
    - logfile
    - stdout


